export const trainingData = [
  {
    id: 68,
    name: "CSPO",
    long_title: "Certified Scrum Product Owner Certification",
    tag_line: "Let's Maximise Value",
    theme_color: "#09236bfa",
    gradient_color_left: "#0000ff",
    gradient_color_right: "#008eff",
    special_class: true,
    seo_slug: "cspo-workshops",
    avatar: "courses/20201102100013/CSPO.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319151301/cspo.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200414135646/cspo_small.png",
    background_image_for_desktop:
      "courses/background/desktop/20190213152358/CSPO.png",
    background_image_for_mobile: "",
    trainings: {
      id: 2411,
      start_date: "2022-10-04T12:00:00Z",
      end_date: "2022-10-06T17:00:00Z",
      training_start_time: "2022-10-04T12:00:00.000Z",
      training_end_time: "2022-10-06T17:00:00.000Z",
      online: true,
      upcoming_past: "No Data",
    },
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 66,
    name: "CSM",
    long_title: "Certified Scrum Master Certification",
    tag_line: "Let's PlayScrum",
    theme_color: "#29196d",
    gradient_color_left: "#29196d",
    gradient_color_right: "#5a0080",
    special_class: true,
    seo_slug: "certified-scrum-master-certification",
    avatar: "courses/csm.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319151220/csm_2.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200414135953/CSM.png",
    background_image_for_desktop:
      "courses/background/desktop/20190212114312/3-large-with-video-thumbnails.png",
    background_image_for_mobile: "",
    trainings: {
      id: 2328,
      start_date: "2022-09-20T08:30:00Z",
      end_date: "2022-09-22T13:30:00Z",
      training_start_time: "2022-09-20T08:30:00.000Z",
      training_end_time: "2022-09-22T13:30:00.000Z",
      online: true,
      upcoming_past: "No Data",
    },
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 72,
    name: "ICP-ACC",
    long_title: "ICAgile Certified Professional - Agile Coaching",
    tag_line: "Coaches Camp",
    theme_color: "#1a3e57",
    gradient_color_left: "#1a3e57",
    gradient_color_right: "#00beda",
    special_class: true,
    seo_slug: "certified-agile-coach",
    avatar: "courses/20210209142127/logo-icp-acc.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319151409/Icp_acc.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200414140119/ic-acc.png",
    background_image_for_desktop:
      "courses/background/desktop/20190213153721/CAC.png",
    background_image_for_mobile:
      "courses/background/mobile/20190423075401/CAC_1.png",
    trainings: {
      id: 2364,
      start_date: "2022-09-30T08:30:00Z",
      end_date: "2022-10-02T16:30:00Z",
      training_start_time: "2022-09-30T08:30:00.000Z",
      training_end_time: "2022-10-02T16:30:00.000Z",
      online: true,
      upcoming_past: "No Data",
    },
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 88,
    name: "A-CSPO",
    long_title: "Advanced Certified Scrum Product Owner",
    tag_line: "Let's MaximizeValue",
    theme_color: "#008fc1",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#008fc1",
    special_class: true,
    seo_slug: "advanced-product-owner-training",
    avatar: "courses/20190401114239/A-CSPO.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152524/ACSPO.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319155513/ACSPO.png",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: {
      id: 2356,
      start_date: "2022-09-27T08:30:00Z",
      end_date: "2022-09-29T13:30:00Z",
      training_start_time: "2022-09-27T08:30:00.000Z",
      training_end_time: "2022-09-29T13:30:00.000Z",
      online: true,
      upcoming_past: "No Data",
    },
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 81,
    name: "A-CSM",
    long_title: "Advanced Certified Scrum Master",
    tag_line: "Show off your SM skills",
    theme_color: "#29196d",
    gradient_color_left: "#29196d",
    gradient_color_right: "#5a0080",
    special_class: true,
    seo_slug: "advanced-scrum-master-training",
    avatar: "courses/20190219143441/SAI_A-CSM_Badge.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319151449/ACSM.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319154741/download_2.png",
    background_image_for_desktop:
      "courses/background/desktop/20190219143441/ACSM-desktop.png",
    background_image_for_mobile:
      "courses/background/mobile/20190219143441/ACSM.png",
    trainings: {
      id: 2358,
      start_date: "2022-10-08T03:30:00Z",
      end_date: "2022-10-09T12:30:00Z",
      training_start_time: "2022-10-08T03:30:00.000Z",
      training_end_time: "2022-10-09T12:30:00.000Z",
      online: true,
      upcoming_past: "No Data",
    },
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 176,
    name: "Product Management Launchpad",
    long_title: "Product Management Launchpad",
    tag_line: "Learn the art of building Products",
    theme_color: "#09236bfa",
    gradient_color_left: "#0000ff",
    gradient_color_right: "#008eff",
    special_class: true,
    seo_slug: "product-management-launchpad",
    avatar: "courses/20201101031613/ICP-PDM.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20201127020212/PDM.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20201127020212/PDM_small.png",
    background_image_for_desktop:
      "courses/background/desktop/20201127020212/PDM-mobile.png",
    background_image_for_mobile: "",
    trainings: {
      id: 2362,
      start_date: "2022-09-23T03:30:00Z",
      end_date: "2022-09-25T10:30:00Z",
      training_start_time: "2022-09-23T03:30:00.000Z",
      training_end_time: "2022-09-25T10:30:00.000Z",
      online: true,
      upcoming_past: "No Data",
    },
    online: true,
    classroom: false,
    e_learning: false,
  },
  {
    id: 172,
    name: "ICP-CAT",
    long_title: "ICAgile Certified Professional - Coaching Agile Transitions",
    tag_line: "Lets Bring the Change",
    theme_color: "#09236bfa",
    gradient_color_left: "#0000ff",
    gradient_color_right: "#008eff",
    special_class: true,
    seo_slug: "coaching-agile-transitions",
    avatar: "courses/20201001171548/ICP-CAT.png",
    card_background_image_for_desktop: "",
    card_background_image_for_mobile: "",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: {
      id: 2365,
      start_date: "2022-10-15T08:30:00Z",
      end_date: "2022-10-16T16:30:00Z",
      training_start_time: "2022-10-15T08:30:00.000Z",
      training_end_time: "2022-10-16T16:30:00.000Z",
      online: true,
      upcoming_past: "No Data",
    },
    online: true,
    classroom: false,
    e_learning: false,
  },
  {
    id: 74,
    name: "TKP",
    long_title: "Team Kanban Practitioner",
    tag_line: "Let's KindleKanban",
    theme_color: "#008fc1",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#008fc1",
    special_class: true,
    seo_slug: "team-kanban-practitioner-tkp-online-training",
    avatar: "courses/20190213161053/TKP.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152252/tkp.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200414140221/TKP.png",
    background_image_for_desktop:
      "courses/background/desktop/20190213160003/TKP.png",
    background_image_for_mobile:
      "courses/background/mobile/20190215150027/TKP_1.png",
    trainings: {
      id: 2414,
      start_date: "2022-09-20T06:00:00Z",
      end_date: "2022-09-21T10:00:00Z",
      training_start_time: "2022-09-20T06:00:00.000Z",
      training_end_time: "2022-09-21T10:00:00.000Z",
      online: true,
      upcoming_past: "No Data",
    },
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 211,
    name: "ICP-ATF",
    long_title: "ICAgile Certified Professional - Agile Team Facilitation",
    tag_line: "Let's learn Facilitation",
    theme_color: "#09236bfa",
    gradient_color_left: "#0000ff",
    gradient_color_right: "#008eff",
    special_class: true,
    seo_slug: "agile-team-facilitation",
    avatar: "courses/20210703162724/ICP-ATF_Blue.png",
    card_background_image_for_desktop: "",
    card_background_image_for_mobile: "",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: {
      id: 2295,
      start_date: "2022-09-24T08:30:00Z",
      end_date: "2022-09-25T16:30:00Z",
      training_start_time: "2022-09-24T08:30:00.000Z",
      training_end_time: "2022-09-25T16:30:00.000Z",
      online: true,
      upcoming_past: "No Data",
    },
    online: true,
    classroom: false,
    e_learning: false,
  },
  {
    id: 79,
    name: "KMP",
    long_title: "Kanban Management Professional (KMP-2)",
    tag_line: "Kanban Management Professional KMP-2",
    theme_color: "#A949A1",
    gradient_color_left: "#A949A1",
    gradient_color_right: "#00beda",
    special_class: true,
    seo_slug: "kanban-management-professional-kmp",
    avatar: "courses/20190215124057/KMP2.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152742/kmp.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319155744/KMP.png",
    background_image_for_desktop:
      "courses/background/desktop/20190215124057/KMP.png",
    background_image_for_mobile:
      "courses/background/mobile/20190215150522/KMP_1.png",
    trainings: {
      id: 2413,
      start_date: "2022-09-24T04:00:00Z",
      end_date: "2022-09-25T13:00:00Z",
      training_start_time: "2022-09-24T04:00:00.000Z",
      training_end_time: "2022-09-25T13:00:00.000Z",
      online: true,
      upcoming_past: "No Data",
    },
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 85,
    name: "CPMP",
    long_title: "Product Management Bootcamp",
    tag_line: "Let's MaximizeValue",
    theme_color: "#008fc1",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#008fc1",
    special_class: true,
    seo_slug: "product-management-bootcamp",
    avatar: "courses/20201102100256/CPMP.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319151105/Product-Management-Workshop.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319154137/download_1.png",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 99,
    name: "CSP-SM",
    long_title: "Certified Scrum Professional - Scrum Master",
    tag_line: "Take your coaching skills to the next level!",
    theme_color: "#29196d",
    gradient_color_left: "#29196d",
    gradient_color_right: "#5a0080",
    special_class: true,
    seo_slug: "certified-scrum-professional-scrum-master",
    avatar: "courses/20190523053810/SAI_BadgeSizes_DigitalBadging_CSP-SM.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319151535/ACSM.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319154814/download_2.png",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 127,
    name: "PMP",
    long_title: "Project Management Professional",
    tag_line: "Learn Project Management",
    theme_color: "#008fc1",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#008fc1",
    special_class: true,
    seo_slug: "project-management-professional-certification",
    avatar: "courses/20200315125906/PMP-Badge.png",
    card_background_image_for_desktop: "",
    card_background_image_for_mobile: "",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: false,
    e_learning: false,
  },
  {
    id: 137,
    name: "PMI-ACP",
    long_title: "PMI-ACP",
    tag_line: "Learn Agile Project Management",
    theme_color: "#008fc1",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#008fc1",
    special_class: true,
    seo_slug: "pmi-acp-certification",
    avatar: "courses/20200424104536/pmi-acp-600px.png",
    card_background_image_for_desktop: "",
    card_background_image_for_mobile: "",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: false,
    e_learning: false,
  },
  {
    id: 114,
    name: "Design Thinking",
    long_title: "Design Thinking",
    tag_line: "Build solutions that users love",
    theme_color: "#008fc1",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#008fc1",
    special_class: true,
    seo_slug: "design-thinking-course",
    avatar: "courses/20191129170723/1.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152120/designthinkingdes.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319155022/download_4.png",
    background_image_for_desktop:
      "courses/background/desktop/20191130120440/Design-Thinking-training-details.png",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 148,
    name: "CI and CD using Jenkins, Ansible, Docker and Kubernetes",
    long_title: "CI and CD using Jenkins, Ansible, Docker and Kubernetes",
    tag_line: "Let's Build value",
    theme_color: "#008fc1",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#008fc1",
    special_class: true,
    seo_slug: "ci-cd-using-jenkins-ansible-docker-and-kubernetes",
    avatar: "courses/20201022125156/CI_CD.png",
    card_background_image_for_desktop: "",
    card_background_image_for_mobile: "",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 73,
    name: "ICP-TST",
    long_title: "ICAgile Certified Professional - Agile Testing",
    tag_line: "Let's Maximize Quality",
    theme_color: "#3041F8",
    gradient_color_left: "#3041F8",
    gradient_color_right: "#59a2fa",
    special_class: true,
    seo_slug: "agile-testing-workshop-icp-tst",
    avatar: "courses/20210209142100/logo-icp-tst.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152713/icp_tst.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319155650/ICP--TST.png",
    background_image_for_desktop:
      "courses/background/desktop/20190213153625/CAT.png",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 69,
    name: "CSD with AWS",
    long_title: "Certified Scrum Developer with AWS",
    tag_line: "Let's Build Value",
    theme_color: "#0a497b",
    gradient_color_left: "#0a497b",
    gradient_color_right: "#1185e0",
    special_class: true,
    seo_slug: "csd-workshop",
    avatar: "courses/20201102083856/CSD.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152208/csd.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319155113/CSD.png",
    background_image_for_desktop:
      "courses/background/desktop/20190213153519/CSD.png",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 82,
    name: "Certified Team Leadership",
    long_title: "Certified Team Leadership",
    tag_line: "Let's Solve Team Dysfunctions",
    theme_color: "#1094c4",
    gradient_color_left: "#1094c4",
    gradient_color_right: "#00cef5",
    special_class: true,
    seo_slug: "certified-team-leadership",
    avatar: "courses/20190408105753/CTL.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152936/For-Leadership.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319160159/download_5.png",
    background_image_for_desktop:
      "courses/background/desktop/20190226081626/1.png",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 76,
    name: "JIRA User Workshop",
    long_title: "JIRA User Workshop",
    tag_line: "JIRA User Workshop",
    theme_color: "#b64aae",
    gradient_color_left: "#93448E",
    gradient_color_right: "#FB54EE",
    special_class: true,
    seo_slug: "jira-user-training",
    avatar: "courses/20190213105826/jira_icon.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152624/Jira-User-Workshop.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319155610/Jira-User-Workshop.png",
    background_image_for_desktop:
      "courses/background/desktop/20190213153110/JUW.png",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 78,
    name: "KSD",
    long_title: "Kanban System Design (KMP-1)",
    tag_line: "Kanban System Design KMP-1",
    theme_color: "#008fc1",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#00beda",
    special_class: true,
    seo_slug: "kanban-system-design",
    avatar: "courses/20190215122449/LKU-logo.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152816/ksd.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319155817/ksd.png",
    background_image_for_desktop:
      "courses/background/desktop/20190215122450/KSD.png",
    background_image_for_mobile:
      "courses/background/mobile/20190215145944/KSD_1.png",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 219,
    name: "Scrum@Scale Practitioner",
    long_title: "Scrum at Scale Practitioner",
    tag_line: "Let's Scale Scrum!",
    theme_color: "#29196d",
    gradient_color_left: "#29196d",
    gradient_color_right: "#5a0080",
    special_class: true,
    seo_slug: "scrum-at-scale-practitioner",
    avatar: "courses/20210816162847/SAS-R3-ALT2-01_500px-2048x2048.png",
    card_background_image_for_desktop: "",
    card_background_image_for_mobile: "",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 84,
    name: "ICP-FDO",
    long_title: "ICAgile Certified Professional - Foundations of DevOps",
    tag_line: "Let's Build Value",
    theme_color: "#0a497b",
    gradient_color_left: "#0a497b",
    gradient_color_right: "#1185e0",
    special_class: true,
    seo_slug: "devops-certification-training",
    avatar: "courses/20210209141539/logo-icp-fdo.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319151754/devops.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319154950/download_3.png",
    background_image_for_desktop:
      "courses/background/desktop/20190912110651/CAT.png",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 212,
    name: "Build MVP without Code",
    long_title: "Build MVP without Code",
    tag_line: "Validate your MVP without coding",
    theme_color: "#008fc1",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#008fc1",
    special_class: true,
    seo_slug: "build-mvp-without-code",
    avatar: "courses/20210727020331/Asset_14x.png",
    card_background_image_for_desktop: "",
    card_background_image_for_mobile: "",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 75,
    name: "JIRA Admin Workshop",
    long_title: "JIRA Admin Workshop",
    tag_line: "JIRA Admin Workshop",
    theme_color: "#bc9761",
    gradient_color_left: "#bc9761",
    gradient_color_right: "#00beda",
    special_class: true,
    seo_slug: "jira-admin-training",
    avatar: "courses/20190213105704/jira_icon.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319153004/jira.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319160250/jira.png",
    background_image_for_desktop:
      "courses/background/desktop/20190213153131/JIRA.png",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 121,
    name: "Design Thinking Basics",
    long_title: "Design Thinking Basics",
    tag_line: "Get started with Design Thinking",
    theme_color: "#008fc1",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#008fc1",
    special_class: true,
    seo_slug: "design-thinking-basics",
    avatar: "courses/20200503070433/Foundation-of-DT.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200502090940/designthinkingdes.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200502090940/download_4.png",
    background_image_for_desktop:
      "courses/background/desktop/20200502090940/Design-Thinking-training-details.png",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: false,
    e_learning: false,
  },
  {
    id: 87,
    name: "Leading SAFe",
    long_title: "Certified SAFe® Agilist 5.0",
    tag_line: "Leading SAFe",
    theme_color: "#1DA2CC",
    gradient_color_left: "#1DA2CC",
    gradient_color_right: "blue",
    special_class: true,
    seo_slug: "safe-agilist-certification-training",
    avatar: "courses/20200305083239/leadingsafe5-removebg-preview.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152424/Dysfunctions-for-team.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319155411/DYSFUNCTIONS-for-team.png",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 93,
    name: "Certified NLP Practitioner - Level I",
    long_title: "Certified NLP Practitioner - Level I",
    tag_line: "Self Transformation Camp",
    theme_color: "#1DA2CC",
    gradient_color_left: "#1DA2CC",
    gradient_color_right: "blue",
    special_class: true,
    seo_slug: "certified-nlp-practitioner",
    avatar: "courses/20190409113406/nlp.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152554/NLP.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319155540/NLP.png",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 80,
    name: "Scrum Fundamentals",
    long_title: "Scrum Fundamentals",
    tag_line: "Get your basics right!!",
    theme_color: "#29196d",
    gradient_color_left: "#29196d",
    gradient_color_right: "#5a0080",
    special_class: true,
    seo_slug: "scrum-fundamentals",
    avatar:
      "courses/20201207155908/Scrum-essentials-min-removebg-preview_1.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319153404/Scrum-Fundamentals.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319160541/Scrum-Fundamentals.png",
    background_image_for_desktop:
      "courses/background/desktop/20190219100355/Scrum-Funda.jpg",
    background_image_for_mobile:
      "courses/background/mobile/20190219102602/SF.png",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 104,
    name: "AWS Certified Solution Architect - Associate",
    long_title: "AWS Certified Solution Architect - Associate Prep Course",
    tag_line: "AWS Certified Solution Architect - Associate Prep Course",
    theme_color: "#807e7e",
    gradient_color_left: "#e6733a",
    gradient_color_right: "#b63688",
    special_class: true,
    seo_slug: "aws-certified-solution-architect-associate",
    avatar: "courses/20190812183616/logo.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152322/aws-cloud.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319155308/aws-cloud.png",
    background_image_for_desktop:
      "courses/background/desktop/20190908180521/aws-cloud.jpg",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 113,
    name: "CI and CD Workshop",
    long_title: "CI and CD Workshop",
    tag_line: "Let's Build Value",
    theme_color: "#008fc1",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#008fc1",
    special_class: true,
    seo_slug: "ci-and-cd-workshop",
    avatar: "courses/20201022121516/CI_CD.png",
    card_background_image_for_desktop: "",
    card_background_image_for_mobile: "",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 229,
    name: "Python",
    long_title: "Python",
    tag_line: "Let's Integrate more system!",
    theme_color: "#1094c4",
    gradient_color_left: "#1094c4",
    gradient_color_right: "#1094c4",
    special_class: true,
    seo_slug: "learning-python",
    avatar: "courses/20211116132443/python-logo.png",
    card_background_image_for_desktop: "",
    card_background_image_for_mobile: "",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: false,
    e_learning: false,
  },
  {
    id: 103,
    name: "AWS Certified Cloud Practitioner",
    long_title: "AWS Certified Cloud Practitioner Prep Course",
    tag_line: "AWS Cloud Practitioner Prep Course",
    theme_color: "#807e7e",
    gradient_color_left: "#e6733a",
    gradient_color_right: "#b63688",
    special_class: true,
    seo_slug: "aws-certified-cloud-practitioner",
    avatar: "courses/20190719183004/aws-cloud-prac.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319152338/aws-cloud.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319155331/aws-cloud.png",
    background_image_for_desktop:
      "courses/background/desktop/20190730111107/aws-cloud.jpg",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 91,
    name: "Bitbucket Workshop",
    long_title: "Bitbucket Workshop",
    tag_line: "Bitbucket Workshop",
    theme_color: "#1DA2CC",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#00beda",
    special_class: true,
    seo_slug: "bitbucket-workshop",
    avatar: "courses/20190404135005/Bitbucket2x-blue.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319153241/Jira-User-Workshop.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319160440/Jira-User-Workshop.png",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 92,
    name: "Bamboo Workshop",
    long_title: "Bamboo Workshop",
    tag_line: "Bamboo Workshop",
    theme_color: "#1DA2CC",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#00beda",
    special_class: true,
    seo_slug: "bamboo-workshop",
    avatar: "courses/20190404142751/Bamboo2x-blue.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319153308/Atlassan-tools-training.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319160510/Atlassan-tools.png",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 89,
    name: "Confluence User Workshop",
    long_title: "Confluence User Workshop",
    tag_line: "Confluence User Workshop",
    theme_color: "#1DA2CC",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#00beda",
    special_class: true,
    seo_slug: "confluence-user-workshop",
    avatar: "courses/20190404102550/Confluence2x-blue.png",
    card_background_image_for_desktop:
      "courses/background/desktop/20200319153206/Atlassan-tools-training.png",
    card_background_image_for_mobile:
      "courses/background/mobile/20200319160408/Atlassan-tools.png",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: true,
    e_learning: false,
  },
  {
    id: 135,
    name: "Jenkins Fundamentals",
    long_title: "Jenkins Fundamentals",
    tag_line: "Streamline Build and CI",
    theme_color: "#008fc1",
    gradient_color_left: "#3017ff",
    gradient_color_right: "#008fc1",
    special_class: true,
    seo_slug: "jenkins-fundamentals",
    avatar: "courses/20200407122855/Untitled-1.png",
    card_background_image_for_desktop: "",
    card_background_image_for_mobile: "",
    background_image_for_desktop: "",
    background_image_for_mobile: "",
    trainings: [],
    online: true,
    classroom: false,
    e_learning: false,
  },
];
